import { useState, useEffect } from 'react';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { db } from './firebase';
import { BusinessSettings } from '../types';

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  companyName: 'ProEase Enterprise Pte Ltd',
  registrationNumber: '202412345M',
  taxId: 'GST-REG-98765432',
  address: '10 Marina Boulevard, #22-01 Marina Bay Financial Centre, Singapore 018983',
  contactEmail: 'finance@proease-erp.com',
  contactPhone: '+65 6789 0123',
  logoUrl: '',
  operatingCountry: 'SG',
  headerTagline: 'Next-Generation SME Resource Planning & Retail POS Engine',
  footerNote: 'This document is officially generated by ProEaseERP. Authorized & recorded under regional commercial registry laws.',
  isPremiumSubscriber: true,
  officeLatitude: 1.2801,
  officeLongitude: 103.8540,
  geofenceRadiusMeters: 300,
  authorizedWifiSsid: 'ProEase_Corp_Secure',
  authorizedWifiBssids: ['00:11:22:33:44:55', 'aa:bb:cc:dd:ee:ff'],
  currencySymbol: 'S$',
  gstRate: 9,
  sstRate: 8,
};

export function useBusinessSettings() {
  const [settings, setSettings] = useState<BusinessSettings>(DEFAULT_BUSINESS_SETTINGS);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const unsub = onSnapshot(
      doc(db, 'settings', 'business'),
      (snapshot) => {
        if (snapshot.exists()) {
          const data = snapshot.data() as Partial<BusinessSettings>;
          setSettings({
            ...DEFAULT_BUSINESS_SETTINGS,
            ...data,
          });
        } else {
          // Initialize if document does not exist yet
          setDoc(doc(db, 'settings', 'business'), DEFAULT_BUSINESS_SETTINGS).catch(console.error);
        }
        setLoading(false);
      },
      (err) => {
        console.warn('Could not load business settings, using defaults:', err);
        setLoading(false);
      }
    );

    return () => unsub();
  }, []);

  const updateSettings = async (newSettings: Partial<BusinessSettings>) => {
    await setDoc(doc(db, 'settings', 'business'), newSettings, { merge: true });
  };

  return { settings, loading, updateSettings };
}
